name: Assign Team Based on Label

on:
  issue_comment:
    types: [created]

jobs:
  assign-team:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Assign team based on label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.INVITE_TOKEN }}
          script: |
            const issueNumber = context.payload.issue.number;
            const labels = context.payload.issue.labels.map(l => l.name);
            const username = context.payload.issue.user.login;
            const message = context.payload.comment.body;
            const isLocked = context.payload.issue.locked;

            if(context.payload.comment.user.login !== username || isLocked || !message.toLowerCase().includes("done")){
              return
            }

            // Map labels to team mentions
            const teamMap = {
              "Programmer": "programming-team",
              "Security Analysts": "cyber-security-team",
              "Creatives": "creatives",
              "Documentation": "documentation-team"
            };

            let teamSlug = null;
            for (const label of labels) {
              if (teamMap[label]) {
                teamSlug = teamMap[label];
                break;
              }
            }


            if(teamSlug){
              await github.rest.teams.addOrUpdateMembershipForUserInOrg({
                org: "itparadigmdll",
                team_slug: teamSlug,
                username: username,
                role: "member"
              });

              for (const label of labels) {
                if (teamMap[label]) {
                  // Add a comment tagging the team
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issueNumber,
                    body: `Hi @${username}, you are now added to @itparadigmdll/${teamMap[label]}. Thank you for joining with us, and keep grinding and sharing.`
                  });
                }
              }
            }

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              state: "closed"
            });

